In [40]:
import pandas as pd
import numpy as np
from itertools import product

In [ ]:
df = pd.read_csv("data/combined/all_sc.tsv", sep="\t")
df = df[["Intensity", "sector", "Ion Type"]]
df

In [ ]:
df_b = df[df["Ion Type"] == "b"]
df_b = df_b[["Intensity", "sector"]]

df_y = df[df["Ion Type"] == "y"]
df_y = df_y[["Intensity", "sector"]]

b_counts = pd.DataFrame(df_b.value_counts())
b_counts = b_counts.reset_index()
b_counts.rename(columns = {0:'counts'}, inplace = True)
b_counts

In [ ]:
y_counts = pd.DataFrame(df_y.value_counts())
y_counts.rename(columns = {0:'counts'}, inplace = True)
y_counts = y_counts.reset_index()
y_counts

In [ ]:
intensities = ["none", "low", "medium", "high"]
sectors = [1, 2, 3]

df_template = pd.DataFrame(product(intensities, sectors), columns=["Intensity", "sector"])
b_template = df_template.copy()
y_template = df_template.copy()
df_template

In [87]:
b = pd.merge(b_template, b_counts, on=["Intensity", "sector"], how="outer")
b_counts_sum = b.counts.sum()
b.counts = b.counts.apply(lambda x: x / b_counts_sum)
b

   Intensity  sector    counts
0       none       1  0.261711
1       none       2  0.357624
2       none       3  0.146135
3        low       1  0.141427
4        low       2  0.038929
5        low       3  0.002110
6     medium       1  0.030390
7     medium       2  0.005523
8     medium       3  0.000113
9       high       1  0.013573
10      high       2  0.002443
11      high       3  0.000021

In [84]:
y = pd.merge(y_template, y_counts, on=["Intensity", "sector"], how="outer")
y_counts_sum = y.counts.sum()
y.counts = y.counts.apply(lambda x: x / y_counts_sum)
y

   Intensity  sector    counts
0       none       1  0.089711
1       none       2  0.087303
2       none       3  0.114861
3        low       1  0.274860
4        low       2  0.210009
5        low       3  0.025993
6     medium       1  0.039517
7     medium       2  0.082864
8     medium       3  0.007073
9       high       1  0.012462
10      high       2  0.052000
11      high       3  0.003349